steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/maheshkumarrp/gcpdemo.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/edureka-gcp-training-mahesh/mybuilder:latest', '.']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/my-deployment'
  - 'my-container=gcr.io/edureka-gcp-training-mahesh/mybuilder:latest'

images: ['gcr.io/edureka-gcp-training-mahesh/mybuilder:latest']  