steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/maheshkumarrp/gcpdemo.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT}/${CONTAINER}:${VERSION}', '.']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${DEPLOYMENT}'
  - '${CONTAINER}=gcr.io/${PROJECT}/${CONTAINER}:${VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
  
substitutions:
    PROJECT: edureka-gcp-training-mahesh
    DEPLOYMENT: my-deployment
    CONTAINER: mybuilder
    VERSION: v4.0    
    
options:
    substitution_option: 'ALLOW_LOOSE'
    
images: ['gcr.io/edureka-gcp-training-mahesh/mybuilder:v3.0']