steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/maheshkumarrp/gcpdemo.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}', '.']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
  
substitutions:
    _PROJECT: edureka-gcp-training-mahesh
    _DEPLOYMENTNAME: my-deployment
    _CONTAINERNAME: mybuilder
    _VERSION: v4.0    
    
options:
    substitution_option: 'ALLOW_LOOSE'
    
images: ['gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']