steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/maheshkumarrp/gcpdemo.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT}/${CONTAINERNAME}:${VERSION}', '.']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${DEPLOYMENTNAME}'
  - '${CONTAINERNAME}=gcr.io/${PROJECT}/${CONTAINERNAME}:${VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
  
substitutions:
    'PROJECT': 'edureka-gcp-training-mahesh'
    'DEPLOYMENTNAME': 'my-deployment'
    'CONTAINERNAME': 'mybuilder'
    'VERSION': 'v4.0'    
    
options:
    substitution_option: 'ALLOW_LOOSE'
    
images: ['gcr.io/edureka-gcp-training-mahesh/mybuilder:v3.0']